environment:
  machine_user: test_user
  machine_pass: Pass@word1
  CTEST_OUTPUT_ON_FAILURE: 1
  CC: clang
  CXX: clang++

  matrix:
    - BUILD_TYPE: release
      STATIC_LIBRARIES: FALSE

install:
  - C:\cygwin\setup-x86.exe --quiet-mode --no-shortcuts --no-startmenu --no-desktop --upgrade-also --only-site --site http://cygwin.mirror.constant.com/ --packages clang-3.8.1-1,cmake-3.6.2-1,make,python3,git-2.8.3-1

build_script:
  - c:\cygwin\bin\sh -c '.cygwin/build.sh'