environment:
  machine_user: test_user
  machine_pass: Pass@word1
  CTEST_OUTPUT_ON_FAILURE: 1
  CC: clang
  CXX: clang++

  matrix:
    - BUILD_TYPE: release
      STATIC_LIBRARIES: FALSE

install:
  - C:\cygwin\setup-x86.exe -q --packages clang-3.8.1-1,cmake-3.6.2-1,make-4.2.1-1,git-2.8.3-1,python3-3.4.3-1

build_script:
  - c:\cygwin\bin\bash .cygwin/build.sh