environment:
  machine_user: test_user
  machine_pass: Pass@word1
  CTEST_OUTPUT_ON_FAILURE: 1
  CC: clang
  CXX: clang++
  global:
    CYG_ROOT: C:\cygwin
    CYG_MIRROR: http://cygwin.mirror.constant.com
    CYG_CACHE: C:\cygwin\var\cache\setup
    CYG_BASH: C:\cygwin\bin\bash

  matrix:
    - BUILD_TYPE: release
      STATIC_LIBRARIES: FALSE

cache:
    - '%CYG_CACHE%'

install:
  - C:\cygwin\setup-x86.exe -q --root "%CYG_ROOT%" --site "%CYG_MIRROR%" --local-package-dir "%CYG_CACHE%" --packages clang,cmake,make,git,python3

build_script:
  - %CYG_BASH% .cygwin/build.sh