cache:
  - c:\cygwin-setup-cache

environment:
  machine_user: test_user
  machine_pass: Pass@word1
  CTEST_OUTPUT_ON_FAILURE: 1
  cygwin_url: https://cygwin.com/setup-x86_64.exe
  CC: clang
  CXX: clang++

  matrix:
    - BUILD_TYPE: release
      STATIC_LIBRARIES: FALSE

install:
  - ps: Invoke-WebRequest $env:cygwin_url -OutFile c:\cygwin-setup.exe
  - c:\cygwin-setup.exe --quiet-mode --no-shortcuts --no-startmenu --no-desktop --upgrade-also --only-site --site http://cygwin.mirror.constant.com/ --root c:\cygwin-root --local-package-dir c:\cygwin-setup-cache --packages clang-3.8.1-1,cmake-3.6.2-1,make,python3,git-2.8.3-1

build_script:
  - c:\cygwin-root\bin\sh .cygwin/build.sh